/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.api.tasks.JavaExec

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    `maven-publish`
    id("hytale-mod") version "0.5.1-alpha"
}

group = "com.adesi"
version = "0.1-SNAPSHOT"
val projectname = "MagicalScience"

val javaVersion = 25
val appData = System.getenv("APPDATA") ?: (System.getenv("HOME") + "/.var/app/com.hypixel.HytaleLauncher/data")
val hytaleAssets = file("$appData/Hytale/install/release/package/game/latest/Assets.zip")

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://maven.hytale-modding.info/releases") {
        name = "HytaleModdingReleases"
    }
}
dependencies {

    compileOnly(libs.jetbrains.annotations)
    compileOnly(libs.jspecify)

    if (hytaleAssets.exists()) {
        compileOnly(files(hytaleAssets))
    } else {
        // Optional: Print a warning so you know why it's missing
        logger.warn("Hytale Assets.zip not found at: ${hytaleAssets.absolutePath}")
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }

    withSourcesJar()
}

hytale {
    programArgs.add(
        "--mods=" +
            layout.projectDirectory
                .dir("src/main/")
                .asFile.absolutePath,
    )
    updateChannel = "pre-release"
}

tasks.withType<Jar> {
    manifest {
        attributes["Specification-Title"] = rootProject.name
        attributes["Specification-Version"] = version
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] =
            providers
                .environmentVariable("COMMIT_SHA_SHORT")
                .map { "$version-$it" }
                .getOrElse(version.toString())
    }
}

publishing {
    repositories {
        // This is where you put repositories that you want to publish to.
        // Do NOT put repositories for your dependencies here.
    }

    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
