/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.api.tasks.JavaExec

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    `maven-publish`
    id("hytale-mod") version "0.4.3-alpha"
}

group = "com.adesi"
version = "0.1-SNAPSHOT"
val projectname = "MagicalScience"

val javaVersion = 25
val appData = System.getenv("APPDATA") ?: (System.getenv("HOME") + "/.var/app/com.hypixel.HytaleLauncher/data")
val hytaleAssets = file("$appData/Hytale/install/release/package/game/latest/Assets.zip")

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://maven.hytale-modding.info/releases") {
        name = "HytaleModdingReleases"
    }
}
dependencies {

    compileOnly(libs.jetbrains.annotations)
    compileOnly(libs.jspecify)

    if (hytaleAssets.exists()) {
        compileOnly(files(hytaleAssets))
    } else {
        // Optional: Print a warning so you know why it's missing
        logger.warn("Hytale Assets.zip not found at: ${hytaleAssets.absolutePath}")
    }
}
// tasks.named<Jar>("jar") {
//     destinationDirectory.set(file("/home/adesi/.var/app/com.hypixel.HytaleLauncher/data/Hytale/UserData/Mods"))
// }
//
// tasks.register<JavaExec>("decompileServer") {
//     group = "hytale"
//     description = "Decompile HytaleServer.jar into a sources zip"
//
//     val serverJar = file("libs/HytaleServer.jar")
//     val sourcesZip = file("libs/HytaleServer-sources.zip")
//
//     workingDir = temporaryDir
//     mainClass.set("org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler")
//     classpath = vineFlowerDependencies
//
//     args(
//         serverJar.absolutePath,
//         sourcesZip.absolutePath,
//     )
//
//     inputs.file(serverJar)
//     outputs.file(sourcesZip)
// }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }

    withSourcesJar()
}

tasks.named<ProcessResources>("processResources") {
    var replaceProperties =
        mapOf(
            "plugin_group" to findProperty("plugin_group"),
            "plugin_maven_group" to project.group,
            "plugin_name" to projectname,
            "plugin_version" to project.version,
            "server_version" to findProperty("server_version"),
            "plugin_description" to findProperty("plugin_description"),
            "plugin_website" to findProperty("plugin_website"),
            "plugin_main_entrypoint" to findProperty("plugin_main_entrypoint"),
            "plugin_author" to findProperty("plugin_author"),
        )

    filesMatching("manifest.json") {
        expand(replaceProperties)
    }

    inputs.properties(replaceProperties)
}

hytale {
}

tasks.withType<Jar> {
    manifest {
        attributes["Specification-Title"] = rootProject.name
        attributes["Specification-Version"] = version
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] =
            providers
                .environmentVariable("COMMIT_SHA_SHORT")
                .map { "$version-$it" }
                .getOrElse(version.toString())
    }
}

publishing {
    repositories {
        // This is where you put repositories that you want to publish to.
        // Do NOT put repositories for your dependencies here.
    }

    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

val syncAssets =
    tasks.register<Copy>("syncAssets") {
        group = "hytale"
        description = "Automatically syncs assets from Build back to Source after server stops."

        // Take from the temporary build folder (Where the game saved changes)
        from(layout.buildDirectory.dir("resources/main"))

        // Copy into your actual project source (Where your code lives)
        into("src/main/resources")

        // IMPORTANT: Protect the manifest template from being overwritten
        exclude("manifest.json")

        // If a file exists, overwrite it with the new version from the game
        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        doLast {
            println("✅ Assets successfully synced from Game to Source Code!")
        }
    }

afterEvaluate {
    // Now Gradle will find it, because the plugin has finished working
    val targetTask = tasks.findByName("runServer") ?: tasks.findByName("server")

    if (targetTask != null) {
        targetTask.finalizedBy(syncAssets)
        logger.lifecycle("✅ specific task '${targetTask.name}' hooked for auto-sync.")
    } else {
        logger.warn("⚠️ Could not find 'runServer' or 'server' task to hook auto-sync into.")
    }
}
